### ISSUE TITLE
Make generated keymap code more human-friendly

### ISSUE THREAD

**Issue by vomindoraan** [qmk/qmk_compiler#25]
Consider removing

    // Helpful defines
    #define _______ KC_TRNS

from the generated source since the alias is already defined in `quantum_keycodes.h`.

Also, consider replacing `KC_NO` and `KC_TRNS` in the code with `XXXXXXX` and `_______`, respectively. Furthermore, add line breaks to the keymaps to make them easier to read ([example](https://gist.github.com/vomindoraan/d4759d591d8499d17e5dc64dc7756ec9)).

The reasoning here is that a lot of people use the Configurator to get a quick start with QMK, and then move on to editing the generated source by hand. It would be helpful to have the keymaps generated in a human-friendly format because of that.

**Comment by skullydazed** [comment]
This should be fixed now, we've moved this functionality to the CLI, which the API uses to compile.
